#############################################################################
# Makefile for building: OmnimagnetSupportVisualizer
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue May 19 08:50:43 2015
# Project:  OmnimagnetSupportVisualizer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile OmnimagnetSupportVisualizer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/local/include/eigen3 -I../Sandbox -I/usr/X11R6/include -IBuild -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -L/usr/lib -lGLU -L../Math_Lib -L../AD_IO_Lib -lAD_IO -lMath -lserial -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = Build/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		GraphicsView3D.cpp \
		model.cpp \
		Assembly.cpp \
		OmnimagnetFrameScene.cpp \
		OpenGL_Object.cpp \
		virticalSupportAssy.cpp \
		horizontalSupportAssy.cpp \
		omnimagnetAssy.cpp \
		baseAssy.cpp \
		ArduinoUSBInterface.cpp \
		../../../media/Telerobotics/code/Sandbox/Utilities/Thread.cpp Build/moc_mainwindow.cpp \
		Build/moc_OmnimagnetFrameScene.cpp
OBJECTS       = Build/main.o \
		Build/mainwindow.o \
		Build/GraphicsView3D.o \
		Build/model.o \
		Build/Assembly.o \
		Build/OmnimagnetFrameScene.o \
		Build/OpenGL_Object.o \
		Build/virticalSupportAssy.o \
		Build/horizontalSupportAssy.o \
		Build/omnimagnetAssy.o \
		Build/baseAssy.o \
		Build/ArduinoUSBInterface.o \
		Build/Thread.o \
		Build/moc_mainwindow.o \
		Build/moc_OmnimagnetFrameScene.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		OmnimagnetSupportVisualizer.pro
QMAKE_TARGET  = OmnimagnetSupportVisualizer
DESTDIR       = 
TARGET        = OmnimagnetSupportVisualizer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: OmnimagnetSupportVisualizer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile OmnimagnetSupportVisualizer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile OmnimagnetSupportVisualizer.pro

dist: 
	@$(CHK_DIR_EXISTS) Build/OmnimagnetSupportVisualizer1.0.0 || $(MKDIR) Build/OmnimagnetSupportVisualizer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) Build/OmnimagnetSupportVisualizer1.0.0/ && $(COPY_FILE) --parents mainwindow.h GraphicsView3D.h point3d.h model.h Assembly.h OpenGL_Object.h OmnimagnetFrameScene.h virticalSupportAssy.h horizontalSupportAssy.h omnimagnetAssy.h baseAssy.h ArduinoUSBInterface.h ../../../media/Telerobotics/code/Sandbox/Utilities/Thread.h Build/OmnimagnetSupportVisualizer1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp GraphicsView3D.cpp model.cpp Assembly.cpp OmnimagnetFrameScene.cpp OpenGL_Object.cpp virticalSupportAssy.cpp horizontalSupportAssy.cpp omnimagnetAssy.cpp baseAssy.cpp ArduinoUSBInterface.cpp ../../../media/Telerobotics/code/Sandbox/Utilities/Thread.cpp Build/OmnimagnetSupportVisualizer1.0.0/ && $(COPY_FILE) --parents mainwindow.ui Build/OmnimagnetSupportVisualizer1.0.0/ && (cd `dirname Build/OmnimagnetSupportVisualizer1.0.0` && $(TAR) OmnimagnetSupportVisualizer1.0.0.tar OmnimagnetSupportVisualizer1.0.0 && $(COMPRESS) OmnimagnetSupportVisualizer1.0.0.tar) && $(MOVE) `dirname Build/OmnimagnetSupportVisualizer1.0.0`/OmnimagnetSupportVisualizer1.0.0.tar.gz . && $(DEL_FILE) -r Build/OmnimagnetSupportVisualizer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: Build/moc_mainwindow.cpp Build/moc_OmnimagnetFrameScene.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) Build/moc_mainwindow.cpp Build/moc_OmnimagnetFrameScene.cpp
Build/moc_mainwindow.cpp: OmnimagnetFrameScene.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		model.h \
		point3d.h \
		Assembly.h \
		baseAssy.h \
		virticalSupportAssy.h \
		horizontalSupportAssy.h \
		omnimagnetAssy.h \
		ArduinoUSBInterface.h \
		../Sandbox/Utilities/Thread.h \
		../Sandbox/Utilities/utilities.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o Build/moc_mainwindow.cpp

Build/moc_OmnimagnetFrameScene.cpp: OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		model.h \
		point3d.h \
		Assembly.h \
		baseAssy.h \
		virticalSupportAssy.h \
		horizontalSupportAssy.h \
		omnimagnetAssy.h \
		OmnimagnetFrameScene.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) OmnimagnetFrameScene.h -o Build/moc_OmnimagnetFrameScene.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		GraphicsView3D.h \
		openglscene.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Build/main.o: main.cpp mainwindow.h \
		OmnimagnetFrameScene.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		model.h \
		point3d.h \
		Assembly.h \
		baseAssy.h \
		virticalSupportAssy.h \
		horizontalSupportAssy.h \
		omnimagnetAssy.h \
		ArduinoUSBInterface.h \
		../Sandbox/Utilities/Thread.h \
		../Sandbox/Utilities/utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/main.o main.cpp

Build/mainwindow.o: mainwindow.cpp mainwindow.h \
		OmnimagnetFrameScene.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		model.h \
		point3d.h \
		Assembly.h \
		baseAssy.h \
		virticalSupportAssy.h \
		horizontalSupportAssy.h \
		omnimagnetAssy.h \
		ArduinoUSBInterface.h \
		../Sandbox/Utilities/Thread.h \
		../Sandbox/Utilities/utilities.h \
		ui_mainwindow.h \
		GraphicsView3D.h \
		openglscene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/mainwindow.o mainwindow.cpp

Build/GraphicsView3D.o: GraphicsView3D.cpp GraphicsView3D.h \
		openglscene.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/GraphicsView3D.o GraphicsView3D.cpp

Build/model.o: model.cpp model.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/model.o model.cpp

Build/Assembly.o: Assembly.cpp Assembly.h \
		model.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/Assembly.o Assembly.cpp

Build/OmnimagnetFrameScene.o: OmnimagnetFrameScene.cpp OmnimagnetFrameScene.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		model.h \
		point3d.h \
		Assembly.h \
		baseAssy.h \
		virticalSupportAssy.h \
		horizontalSupportAssy.h \
		omnimagnetAssy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/OmnimagnetFrameScene.o OmnimagnetFrameScene.cpp

Build/OpenGL_Object.o: OpenGL_Object.cpp OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/OpenGL_Object.o OpenGL_Object.cpp

Build/virticalSupportAssy.o: virticalSupportAssy.cpp virticalSupportAssy.h \
		Assembly.h \
		model.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/virticalSupportAssy.o virticalSupportAssy.cpp

Build/horizontalSupportAssy.o: horizontalSupportAssy.cpp horizontalSupportAssy.h \
		Assembly.h \
		model.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/horizontalSupportAssy.o horizontalSupportAssy.cpp

Build/omnimagnetAssy.o: omnimagnetAssy.cpp omnimagnetAssy.h \
		Assembly.h \
		model.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/omnimagnetAssy.o omnimagnetAssy.cpp

Build/baseAssy.o: baseAssy.cpp baseAssy.h \
		Assembly.h \
		model.h \
		point3d.h \
		OpenGL_Object.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/baseAssy.o baseAssy.cpp

Build/ArduinoUSBInterface.o: ArduinoUSBInterface.cpp ArduinoUSBInterface.h \
		../Sandbox/Utilities/Math.h \
		../Sandbox/Utilities/Math/Angle.h \
		../Sandbox/Utilities/Units.h \
		../Sandbox/Utilities/Units/forceUnits.h \
		../Sandbox/Utilities/Units/torqueUnits.h \
		../Sandbox/Utilities/Units/distanceUnits.h \
		../Sandbox/Utilities/Units/magneticFieldUnits.h \
		../Sandbox/Utilities/Units/dipoleMomentUnits.h \
		../Sandbox/Utilities/Units/angleUnits.h \
		../Sandbox/Utilities/Math/Configuration5DOF.h \
		../Sandbox/Utilities/Math/MathTypes.h \
		../Sandbox/Utilities/Math/Frame.h \
		../Sandbox/Utilities/Math/Position.h \
		../Sandbox/Utilities/Math/Vector.h \
		../Sandbox/Utilities/Math/Distance.h \
		../Sandbox/Utilities/Math/Direction.h \
		../Sandbox/Utilities/Math/SpinningVector.h \
		../Sandbox/Utilities/Timer.h \
		../Sandbox/Utilities/precisionCalendar.h \
		../Sandbox/Utilities/Math/Configuration6DOF.h \
		../Sandbox/Utilities/Math/Orientation.h \
		../Sandbox/Utilities/Math/Displacement.h \
		../Sandbox/Utilities/Math/DipoleMoment.h \
		../Sandbox/Utilities/Math/DipoleMomentVector.h \
		../Sandbox/Utilities/Math/HomogeneousTransform.h \
		../Sandbox/Utilities/Math/DH_Transform.h \
		../Sandbox/Utilities/Math/estimateAffine3D_Constrained.h \
		../Sandbox/Utilities/Math/FieldForce.h \
		../Sandbox/Utilities/Math/ForceVector.h \
		../Sandbox/Utilities/Math/Force.h \
		../Sandbox/Utilities/Math/MagneticFieldVector.h \
		../Sandbox/Utilities/Math/MagneticField.h \
		../Sandbox/Utilities/Math/HysterisisFilter.hpp \
		../Sandbox/Utilities/Math/JointConfiguration.h \
		../Sandbox/Utilities/Math/LowPassFilter.hpp \
		../Sandbox/Utilities/Math/MagneticTool.h \
		../Sandbox/Utilities/Math/Pixel.h \
		../Sandbox/Utilities/Math/PseudoInverse.h \
		../Sandbox/Utilities/Math/ROI.h \
		../Sandbox/Utilities/Math/RotatingToolConfiguration.h \
		../Sandbox/Utilities/Math/SpinningDirection.h \
		../Sandbox/Utilities/Math/Statistics.hpp \
		../Sandbox/Utilities/Math/Torque.h \
		../Sandbox/Utilities/Math/TorqueVector.h \
		../Sandbox/Utilities/Math/UsefulFunctions.hpp \
		../Sandbox/Utilities/Math/Wrench.h \
		../Sandbox/Utilities/Math/OpenCVSupport.hpp \
		../Sandbox/Utilities/Thread.h \
		../Sandbox/Utilities/utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/ArduinoUSBInterface.o ArduinoUSBInterface.cpp

Build/Thread.o: ../../../media/Telerobotics/code/Sandbox/Utilities/Thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/Thread.o ../../../media/Telerobotics/code/Sandbox/Utilities/Thread.cpp

Build/moc_mainwindow.o: Build/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/moc_mainwindow.o Build/moc_mainwindow.cpp

Build/moc_OmnimagnetFrameScene.o: Build/moc_OmnimagnetFrameScene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Build/moc_OmnimagnetFrameScene.o Build/moc_OmnimagnetFrameScene.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

